import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import { dirname, relative, resolve, sep } from 'node:path';
import matter from 'gray-matter';
import Ajv2020, { type ErrorObject } from 'ajv/dist/2020.js';
import schema from '../../schemas/spec.schema.json';
import type {
  AzureServiceRollup,
  ContractBacking,
  ContractReport,
  CostRollup,
  CoverageReport,
  CrossUnitLink,
  EdgeRelation,
  GeneratedEdge,
  GeneratedEntity,
  GeneratedMap,
  GeneratedStage,
  ModuleRollup,
  SpecificationMetadata,
  UnitPairRollup,
  UnitRollup,
  WaveRollup,
} from '../../src/types/specification';

export const GENERATED_HEADER = 'Generated by scripts/generate-map.ts. Do not edit manually.';

export class SpecificationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'SpecificationError';
  }
}

interface ParsedFile {
  metadata: SpecificationMetadata;
  sourcePath: string;
  rawMarkdown: string;
  body: string;
}

const arrayFields = [
  'tags',
  'depends_on',
  'connects_to',
  'reference_elements',
  'reference_map',
  'responsibilities',
  'owns',
  'does_not_own',
  'data_owned',
  'inputs',
  'outputs',
  'permissions',
  'restrictions',
  'failure_behaviour',
  'open_questions',
  'api_contract',
  'events_emitted',
  'events_consumed',
  'external_events_consumed',
  'consumes',
  'modules',
] as const;

const ajv = new Ajv2020({ allErrors: true, useDefaults: true, strict: false });
const validateMetadata = ajv.compile(schema);

function formatValidationErrors(errors: ErrorObject[] | null | undefined): string {
  return (errors ?? [])
    .map((error) => `${error.instancePath || '(front matter)'} ${error.message ?? 'is invalid'}`)
    .join('; ');
}

function relativePath(repositoryRoot: string, filePath: string): string {
  return relative(repositoryRoot, filePath).split(sep).join('/');
}

function isInsideRoot(root: string, candidate: string): boolean {
  const rootWithSeparator = root.endsWith(sep) ? root : `${root}${sep}`;
  return candidate === root || candidate.startsWith(rootWithSeparator);
}

function safeChildPath(root: string, child: string): string {
  const candidate = resolve(root, child);
  if (!isInsideRoot(root, candidate)) {
    throw new SpecificationError(`Specification path escapes permitted root: ${child}`);
  }
  return candidate;
}

export async function discoverMarkdownFiles(specsRoot: string): Promise<string[]> {
  const root = resolve(specsRoot);
  const files: string[] = [];

  async function visit(directory: string): Promise<void> {
    if (!isInsideRoot(root, directory)) {
      throw new SpecificationError(`Specification directory escapes permitted root: ${directory}`);
    }
    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((left, right) => left.name.localeCompare(right.name));
    for (const entry of entries) {
      if (entry.name.startsWith('.')) continue;
      const entryPath = safeChildPath(directory, entry.name);
      if (entry.isDirectory()) await visit(entryPath);
      else if (entry.isFile() && entry.name.toLowerCase().endsWith('.md')) files.push(entryPath);
    }
  }

  await visit(root);
  return files;
}

function assertArrayFields(metadata: SpecificationMetadata, sourcePath: string): void {
  for (const field of arrayFields) {
    if (!Array.isArray(metadata[field])) {
      throw new SpecificationError(`${sourcePath}: ${field} must be an array`);
    }
  }
}

function assertStageShape(metadata: SpecificationMetadata, sourcePath: string): void {
  if (metadata.entity_type !== 'workflow-step') return;
  if (metadata.stage_order === undefined) {
    throw new SpecificationError(`${sourcePath}: a workflow-step requires stage_order`);
  }
  if (metadata.loop === undefined) {
    throw new SpecificationError(`${sourcePath}: a workflow-step requires loop`);
  }
  // WHY: the reference diagram covers the factory only. Runtime stages are this map's
  // extension beyond it, so they declare no elements — and must say so via loop.
  if (metadata.loop === 'runtime') {
    if (metadata.reference_elements.length > 0) {
      throw new SpecificationError(
        `${sourcePath}: a runtime stage lies beyond the reference diagram and cannot declare reference_elements`,
      );
    }
    return;
  }
  if (metadata.reference_elements.length === 0) {
    throw new SpecificationError(`${sourcePath}: a workflow-step must declare reference_elements`);
  }
}

function assertComponentShape(metadata: SpecificationMetadata, sourcePath: string): void {
  if (metadata.workflow_order !== undefined && metadata.workflow_id === undefined) {
    throw new SpecificationError(`${sourcePath}: workflow_order requires workflow_id`);
  }
  if (metadata.entity_type === 'component' && typeof metadata.owner !== 'string') {
    throw new SpecificationError(`${sourcePath}: component owner must be a single string`);
  }
}

export async function parseSpecification(
  filePath: string,
  repositoryRoot: string,
): Promise<ParsedFile> {
  const raw = await readFile(filePath, 'utf8');
  const sourcePath = relativePath(repositoryRoot, filePath);
  let document: matter.GrayMatterFile<string>;
  try {
    document = matter(raw);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    throw new SpecificationError(`${sourcePath}: invalid front matter: ${reason}`);
  }

  if (!validateMetadata(document.data)) {
    throw new SpecificationError(
      `${sourcePath}: invalid front matter: ${formatValidationErrors(validateMetadata.errors)}`,
    );
  }

  const metadata = document.data as unknown as SpecificationMetadata;
  assertArrayFields(metadata, sourcePath);
  assertStageShape(metadata, sourcePath);
  assertComponentShape(metadata, sourcePath);

  return { metadata, sourcePath, rawMarkdown: raw, body: document.content.trim() };
}

function addRelation(
  relationMap: Map<string, { source: string; target: string; relations: Set<EdgeRelation> }>,
  source: string,
  target: string,
  relation: EdgeRelation,
): void {
  const id = `${source}->${target}`;
  const edge = relationMap.get(id) ?? { source, target, relations: new Set<EdgeRelation>() };
  edge.relations.add(relation);
  relationMap.set(id, edge);
}

function validateRelationTargets(specifications: ParsedFile[], knownIds: Set<string>): void {
  for (const specification of specifications) {
    const { depends_on: dependsOn, connects_to: connectsTo } = specification.metadata;
    for (const reference of [...dependsOn, ...connectsTo]) {
      if (!knownIds.has(reference)) {
        throw new SpecificationError(
          `${specification.sourcePath}: unresolved relationship reference "${reference}"`,
        );
      }
    }
  }
}

function validateStageMembership(specifications: ParsedFile[]): void {
  const stageIds = new Set(
    specifications
      .filter(({ metadata }) => metadata.entity_type === 'workflow-step')
      .map(({ metadata }) => metadata.id),
  );
  for (const { metadata, sourcePath } of specifications) {
    const stageId = metadata.workflow_id;
    if (stageId !== undefined && !stageIds.has(stageId)) {
      throw new SpecificationError(`${sourcePath}: workflow_id "${stageId}" is not a stage specification`);
    }
    for (const served of metadata.serves_stages) {
      if (!stageIds.has(served)) {
        throw new SpecificationError(`${sourcePath}: serves_stages "${served}" is not a stage specification`);
      }
      if (served === stageId) {
        throw new SpecificationError(`${sourcePath}: serves_stages repeats its own workflow_id "${served}"`);
      }
    }
  }
}

function validateStageOrdering(specifications: ParsedFile[]): void {
  const seen = new Map<string, Set<number>>();
  for (const { metadata, sourcePath } of specifications) {
    const { workflow_id: stageId, workflow_order: order } = metadata;
    if (stageId === undefined || order === undefined) continue;
    const orders = seen.get(stageId) ?? new Set<number>();
    if (orders.has(order)) {
      throw new SpecificationError(`${sourcePath}: duplicate workflow_order ${order} for ${stageId}`);
    }
    orders.add(order);
    seen.set(stageId, orders);
  }
}

function validateSingleDataOwner(specifications: ParsedFile[]): void {
  const owners = new Map<string, string>();
  for (const { metadata, sourcePath } of specifications) {
    for (const object of metadata.data_owned) {
      const existing = owners.get(object);
      if (existing !== undefined) {
        throw new SpecificationError(
          `${sourcePath}: authoritative data "${object}" is already owned by ${existing}`,
        );
      }
      owners.set(object, metadata.id);
    }
  }
}

function knownReferenceElements(specifications: ParsedFile[]): Set<string> {
  const elements = new Set<string>();
  for (const { metadata } of specifications) {
    for (const element of metadata.reference_elements) elements.add(element);
  }
  return elements;
}

function validateReferenceClaims(specifications: ParsedFile[]): void {
  const elements = knownReferenceElements(specifications);
  for (const { metadata, sourcePath } of specifications) {
    for (const claim of metadata.reference_map) {
      if (!elements.has(claim)) {
        throw new SpecificationError(
          `${sourcePath}: reference_map entry "${claim}" is not declared by any stage`,
        );
      }
    }
  }
}

function unitSpecifications(specifications: ParsedFile[]): ParsedFile[] {
  return specifications.filter(({ metadata }) => metadata.entity_type === 'deployable-unit');
}

function assertUnitShape({ metadata, sourcePath }: ParsedFile): void {
  if (metadata.entity_type !== 'deployable-unit') return;
  if (typeof metadata.repository !== 'string') {
    throw new SpecificationError(`${sourcePath}: a deployable-unit requires a repository`);
  }
  if (metadata.forcing_function === undefined) {
    throw new SpecificationError(
      `${sourcePath}: a deployable-unit requires a forcing_function — absent one, this is a module`,
    );
  }
  if (metadata.modules.length === 0) {
    throw new SpecificationError(`${sourcePath}: a deployable-unit requires at least one module`);
  }
}

// WHY: build_wave means somebody is going to write this. They cannot start without knowing which
// repository it lands in, so the two facts are validated together rather than as a nice-to-have.
function assertPlacement({ metadata, sourcePath }: ParsedFile, units: Map<string, string[]>): void {
  if (metadata.build_wave === undefined) return;
  const unit = metadata.deployable_unit;
  if (unit === undefined || metadata.module === undefined) {
    throw new SpecificationError(`${sourcePath}: a build_wave requires deployable_unit and module`);
  }
  const modules = units.get(unit);
  if (modules === undefined) {
    throw new SpecificationError(`${sourcePath}: deployable_unit "${unit}" is not a deployable-unit specification`);
  }
  if (!modules.includes(metadata.module)) {
    throw new SpecificationError(`${sourcePath}: module "${metadata.module}" is not declared by ${unit}`);
  }
}

function validateUnitPlacement(specifications: ParsedFile[]): void {
  for (const specification of specifications) assertUnitShape(specification);
  const units = new Map(
    unitSpecifications(specifications).map(({ metadata }) => [metadata.id, metadata.modules]),
  );
  for (const specification of specifications) assertPlacement(specification, units);
}

// WHY: a consumer naming an operation its provider does not publish is the exact failure that a
// repository split hides until runtime. Failing generation is what makes the split affordable.
function validateConsumedOperations(specifications: ParsedFile[]): void {
  const published = new Map(
    specifications.map(({ metadata }) => [metadata.id, metadata.api_contract.map((entry) => entry.operation)]),
  );
  for (const { metadata, sourcePath } of specifications) {
    for (const { from, operation } of metadata.consumes) {
      const operations = published.get(from);
      if (operations === undefined) {
        throw new SpecificationError(`${sourcePath}: consumes names unknown provider "${from}"`);
      }
      if (!operations.includes(operation)) {
        throw new SpecificationError(`${sourcePath}: ${from} does not publish operation "${operation}"`);
      }
    }
  }
}

function emittedEvents(specifications: ParsedFile[]): Set<string> {
  const emitted = new Set<string>();
  for (const { metadata } of specifications) for (const event of metadata.events_emitted) emitted.add(event);
  return emitted;
}

function validateEventPairing(specifications: ParsedFile[]): void {
  const emitted = emittedEvents(specifications);
  for (const { metadata, sourcePath } of specifications) {
    for (const event of metadata.events_consumed) {
      if (emitted.has(event)) continue;
      throw new SpecificationError(
        `${sourcePath}: consumes event "${event}" that nothing emits — declare it under external_events_consumed if it originates outside the platform`,
      );
    }
  }
}

function validateSpecifications(specifications: ParsedFile[]): void {
  const knownIds = new Set<string>();
  for (const { metadata, sourcePath } of specifications) {
    if (knownIds.has(metadata.id)) {
      throw new SpecificationError(`${sourcePath}: duplicate entity ID "${metadata.id}"`);
    }
    knownIds.add(metadata.id);
  }
  validateRelationTargets(specifications, knownIds);
  validateStageMembership(specifications);
  validateStageOrdering(specifications);
  validateSingleDataOwner(specifications);
  validateReferenceClaims(specifications);
  validateUnitPlacement(specifications);
  validateConsumedOperations(specifications);
  validateEventPairing(specifications);
}

function memberIds(specifications: ParsedFile[], stageId: string): string[] {
  return specifications
    .filter(({ metadata }) => metadata.workflow_id === stageId)
    .sort((left, right) => (left.metadata.workflow_order ?? 0) - (right.metadata.workflow_order ?? 0))
    .map(({ metadata }) => metadata.id);
}

function reuserIds(specifications: ParsedFile[], stageId: string): string[] {
  return specifications
    .filter(({ metadata }) => metadata.serves_stages.includes(stageId))
    .map(({ metadata }) => metadata.id)
    .sort();
}

function claimantsOf(specifications: ParsedFile[], element: string): string[] {
  return specifications
    .filter(({ metadata }) => metadata.reference_map.includes(element))
    .map(({ metadata }) => metadata.id)
    .sort();
}

function buildStages(specifications: ParsedFile[]): GeneratedStage[] {
  return specifications
    .filter(({ metadata }) => metadata.entity_type === 'workflow-step')
    .map(({ metadata, sourcePath }) => ({
      id: metadata.id,
      name: metadata.name,
      description: metadata.description,
      execSummary: metadata.exec_summary,
      stageOrder: metadata.stage_order ?? 0,
      loop: metadata.loop ?? 'factory',
      sourcePath,
      componentIds: memberIds(specifications, metadata.id),
      reusedComponentIds: reuserIds(specifications, metadata.id),
      referenceElements: metadata.reference_elements.map((element) => ({
        element,
        coveredBy: claimantsOf(specifications, element),
      })),
    }))
    .sort((left, right) => left.stageOrder - right.stageOrder);
}

function buildCoverage(stages: GeneratedStage[]): CoverageReport {
  const elements = stages.flatMap((stage) =>
    stage.referenceElements.map((entry) => ({ stage, entry })),
  );
  const gaps = elements
    .filter(({ entry }) => entry.coveredBy.length === 0)
    .map(({ stage, entry }) => ({ stageId: stage.id, stageName: stage.name, element: entry.element }));
  return { elementCount: elements.length, coveredCount: elements.length - gaps.length, gaps };
}

function membersOfUnit(specifications: ParsedFile[], unitId: string): ParsedFile[] {
  return specifications.filter(({ metadata }) => metadata.deployable_unit === unitId);
}

function rollupModules(members: ParsedFile[], modules: string[]): ModuleRollup[] {
  return modules.map((module) => ({
    module,
    componentIds: members
      .filter(({ metadata }) => metadata.module === module)
      .sort((left, right) => (left.metadata.build_wave ?? 0) - (right.metadata.build_wave ?? 0))
      .map(({ metadata }) => metadata.id),
  }));
}

function sumOver(members: ParsedFile[], read: (metadata: SpecificationMetadata) => number): number {
  return members.reduce((total, { metadata }) => total + read(metadata), 0);
}

function rollupUnit(specifications: ParsedFile[], unit: ParsedFile): UnitRollup {
  const members = membersOfUnit(specifications, unit.metadata.id);
  return {
    id: unit.metadata.id,
    name: unit.metadata.name,
    repository: unit.metadata.repository ?? unit.metadata.id,
    forcingFunction: unit.metadata.forcing_function ?? 'host',
    description: unit.metadata.description,
    execSummary: unit.metadata.exec_summary,
    sourcePath: unit.sourcePath,
    modules: rollupModules(members, unit.metadata.modules),
    componentIds: members.map(({ metadata }) => metadata.id).sort(),
    waves: [...new Set(members.map(({ metadata }) => metadata.build_wave ?? 0))].sort(),
    operationCount: sumOver(members, (metadata) => metadata.api_contract.length),
    monthlyUsdLow: round(sumOver(members, (metadata) => metadata.cost?.monthly_usd_low ?? 0)),
    monthlyUsdHigh: round(sumOver(members, (metadata) => metadata.cost?.monthly_usd_high ?? 0)),
  };
}

function declaredOperations(source: SpecificationMetadata, target: SpecificationMetadata): string[] {
  const outbound = source.consumes.filter((entry) => entry.from === target.id);
  const inbound = target.consumes.filter((entry) => entry.from === source.id);
  return [...outbound, ...inbound].map((entry) => `${entry.from} · ${entry.operation}`).sort();
}

function sharedEvents(source: SpecificationMetadata, target: SpecificationMetadata): string[] {
  const forward = source.events_emitted.filter((event) => target.events_consumed.includes(event));
  const backward = target.events_emitted.filter((event) => source.events_consumed.includes(event));
  return [...new Set([...forward, ...backward])].sort();
}

// WHY: most existing contracts name their caller in prose rather than through a consumes entry.
// Reporting those as inferred keeps the map honest about which pairings are actually machine-checked.
function inferredOperations(source: SpecificationMetadata, target: SpecificationMetadata): string[] {
  return target.api_contract
    .filter((entry) => entry.caller.includes(source.id))
    .map((entry) => `${target.id} · ${entry.operation}`)
    .sort();
}

function backingOf(operations: string[], events: string[], inferred: string[]): ContractBacking {
  if (operations.length > 0) return 'declared';
  if (events.length > 0) return 'event';
  if (inferred.length > 0) return 'inferred';
  return 'none';
}

function linkFor(edge: GeneratedEdge, source: ParsedFile, target: ParsedFile): CrossUnitLink {
  const operations = declaredOperations(source.metadata, target.metadata);
  const events = sharedEvents(source.metadata, target.metadata);
  const inferred = inferredOperations(source.metadata, target.metadata);
  return {
    id: edge.id,
    sourceUnit: source.metadata.deployable_unit ?? '',
    targetUnit: target.metadata.deployable_unit ?? '',
    sourceId: source.metadata.id,
    targetId: target.metadata.id,
    backing: backingOf(operations, events, inferred),
    operations: operations.length > 0 ? operations : inferred,
    events,
  };
}

function rollupPairs(links: CrossUnitLink[]): UnitPairRollup[] {
  const pairs = new Map<string, UnitPairRollup>();
  for (const link of links) {
    const id = `${link.sourceUnit}->${link.targetUnit}`;
    const pair = pairs.get(id) ?? { id, sourceUnit: link.sourceUnit, targetUnit: link.targetUnit, links: [] };
    pair.links.push(link);
    pairs.set(id, pair);
  }
  return [...pairs.values()].sort((left, right) => left.id.localeCompare(right.id));
}

function buildContracts(specifications: ParsedFile[], edges: GeneratedEdge[]): ContractReport {
  const placed = new Map(
    specifications.filter(({ metadata }) => metadata.deployable_unit).map((file) => [file.metadata.id, file]),
  );
  const links: CrossUnitLink[] = [];
  let inUnitCount = 0;
  for (const edge of edges) {
    if (!edge.relations.some((relation) => relation !== 'workflow')) continue;
    const source = placed.get(edge.source);
    const target = placed.get(edge.target);
    if (!source || !target) continue;
    if (source.metadata.deployable_unit === target.metadata.deployable_unit) inUnitCount += 1;
    else links.push(linkFor(edge, source, target));
  }
  return {
    units: unitSpecifications(specifications).map((unit) => rollupUnit(specifications, unit)),
    pairs: rollupPairs(links),
    crossUnitCount: links.length,
    inUnitCount,
    backedCount: links.filter((link) => link.backing === 'declared' || link.backing === 'event').length,
    gaps: links.filter((link) => link.backing === 'none'),
  };
}

function rollupAzure(specifications: ParsedFile[]): AzureServiceRollup[] {
  const lines = new Map<string, AzureServiceRollup>();
  for (const { metadata } of specifications) {
    for (const line of metadata.cost?.azure ?? []) {
      const key = `${line.service}::${line.sku}`;
      const existing = lines.get(key);
      if (existing) {
        existing.usedBy.push(metadata.id);
        continue;
      }
      lines.set(key, {
        service: line.service,
        sku: line.sku,
        monthlyUsdLow: line.monthly_usd_low,
        monthlyUsdHigh: line.monthly_usd_high,
        usedBy: [metadata.id],
        shared: line.shared === true,
      });
    }
  }
  return [...lines.values()].sort((left, right) => left.service.localeCompare(right.service));
}

function rollupWaves(specifications: ParsedFile[]): WaveRollup[] {
  const waves = new Map<number, WaveRollup>();
  for (const { metadata } of specifications) {
    if (metadata.build_wave === undefined) continue;
    const wave = waves.get(metadata.build_wave) ?? {
      wave: metadata.build_wave,
      componentIds: [],
      monthlyUsdLow: 0,
      monthlyUsdHigh: 0,
    };
    wave.componentIds.push(metadata.id);
    wave.monthlyUsdLow += metadata.cost?.monthly_usd_low ?? 0;
    wave.monthlyUsdHigh += metadata.cost?.monthly_usd_high ?? 0;
    waves.set(metadata.build_wave, wave);
  }
  return [...waves.values()].sort((left, right) => left.wave - right.wave);
}

function sumTaskCost(specifications: ParsedFile[], bound: 'low' | 'high'): number {
  const key = bound === 'low' ? 'model_usd_per_task_low' : 'model_usd_per_task_high';
  return specifications.reduce((total, { metadata }) => total + (metadata.cost?.[key] ?? 0), 0);
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

function buildCost(specifications: ParsedFile[]): CostRollup {
  const waves = rollupWaves(specifications);
  return {
    monthlyUsdLow: round(waves.reduce((total, wave) => total + wave.monthlyUsdLow, 0)),
    monthlyUsdHigh: round(waves.reduce((total, wave) => total + wave.monthlyUsdHigh, 0)),
    modelUsdPerTaskLow: round(sumTaskCost(specifications, 'low')),
    modelUsdPerTaskHigh: round(sumTaskCost(specifications, 'high')),
    waves: waves.map((wave) => ({
      ...wave,
      monthlyUsdLow: round(wave.monthlyUsdLow),
      monthlyUsdHigh: round(wave.monthlyUsdHigh),
    })),
    azureServices: rollupAzure(specifications),
  };
}

function buildEdges(specifications: ParsedFile[], stages: GeneratedStage[]) {
  const relationMap = new Map<
    string,
    { source: string; target: string; relations: Set<EdgeRelation> }
  >();
  for (const { metadata } of specifications) {
    for (const target of metadata.depends_on) addRelation(relationMap, metadata.id, target, 'depends_on');
    for (const target of metadata.connects_to) addRelation(relationMap, metadata.id, target, 'connects_to');
  }
  for (const stage of stages) {
    for (let index = 1; index < stage.componentIds.length; index += 1) {
      addRelation(relationMap, stage.componentIds[index - 1], stage.componentIds[index], 'workflow');
    }
  }
  return [...relationMap.values()]
    .map(({ source, target, relations }) => ({
      id: `${source}->${target}`,
      source,
      target,
      relations: [...relations].sort(),
    }))
    .sort((left, right) => left.id.localeCompare(right.id));
}

function buildEntities(specifications: ParsedFile[]): GeneratedEntity[] {
  return specifications
    .map(({ metadata, sourcePath, rawMarkdown, body }) => ({ ...metadata, sourcePath, rawMarkdown, body }))
    .sort((left, right) => left.id.localeCompare(right.id));
}

export function buildMap(specifications: ParsedFile[], schemaId = schema.$id): GeneratedMap {
  validateSpecifications(specifications);
  const stages = buildStages(specifications);
  const coverage = buildCoverage(stages);
  const edges = buildEdges(specifications, stages);
  const entities = buildEntities(specifications);
  const contracts = buildContracts(specifications, edges);

  return {
    generatedHeader: GENERATED_HEADER,
    schemaId,
    entities,
    edges,
    stages,
    coverage,
    contracts,
    cost: buildCost(specifications),
    validation: {
      entityCount: entities.length,
      edgeCount: edges.length,
      stageCount: stages.length,
      coverageGapCount: coverage.gaps.length,
      contractGapCount: contracts.gaps.length,
    },
  };
}

const ENUM_EXPORTS: [string, string, string][] = [
  ['ENTITY_TYPES', 'EntityType', 'entity_type'],
  ['PLANES', 'Plane', 'plane'],
  ['SCOPES', 'Scope', 'scope'],
  ['STATUSES', 'Status', 'status'],
  ['RISKS', 'Risk', 'risk'],
  ['ACTOR_TYPES', 'ActorType', 'actor_type'],
  ['AUTOMATION_LEVELS', 'AutomationLevel', 'automation_level'],
  ['DATA_CLASSIFICATIONS', 'DataClassification', 'data_classification'],
];

function generatedSchemaValues(): string {
  const properties = schema.properties as Record<string, { enum?: string[] }>;
  const constants = ENUM_EXPORTS.map(
    ([name, , property]) => `export const ${name} = ${JSON.stringify(properties[property].enum ?? [])} as const;`,
  ).join('\n\n');
  const types = ENUM_EXPORTS.map(([name, type]) => `export type ${type} = (typeof ${name})[number];`).join('\n');
  return `// GENERATED FILE — DO NOT EDIT MANUALLY. Regenerate with \`npm run generate\`.\n\n${constants}\n\n${types}\n`;
}

export async function generateProjectMap(
  repositoryRoot: string,
  outputPath: string,
  schemaValuesPath: string,
): Promise<GeneratedMap> {
  const files = await discoverMarkdownFiles(resolve(repositoryRoot, 'specs'));
  const specifications: ParsedFile[] = [];
  for (const file of files) specifications.push(await parseSpecification(file, repositoryRoot));
  const map = buildMap(specifications);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, `${JSON.stringify(map, null, 2)}\n`, 'utf8');
  await mkdir(dirname(schemaValuesPath), { recursive: true });
  await writeFile(schemaValuesPath, generatedSchemaValues(), 'utf8');
  return map;
}

export function assertSafeRepositoryPath(repositoryRoot: string, candidate: string): void {
  const root = resolve(repositoryRoot);
  if (!isInsideRoot(root, resolve(candidate))) {
    throw new SpecificationError(`Specification path escapes permitted root: ${candidate}`);
  }
}
