import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import { dirname, relative, resolve, sep } from 'node:path';
import matter from 'gray-matter';
import Ajv2020, { type ErrorObject } from 'ajv/dist/2020.js';
import schema from '../../schemas/spec.schema.json';
import type {
  EdgeRelation,
  GeneratedMap,
  SpecificationMetadata,
  WorkflowTrace,
} from '../../src/types/specification';

export const GENERATED_HEADER =
  'Generated by scripts/generate-map.ts. Do not edit manually.';

export class SpecificationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'SpecificationError';
  }
}

interface ParsedFile {
  metadata: SpecificationMetadata;
  sourcePath: string;
  body: string;
}

const arrayFields = [
  'tags',
  'depends_on',
  'connects_to',
  'responsibilities',
  'owns',
  'does_not_own',
  'inputs',
  'outputs',
  'permissions',
  'restrictions',
  'failure_behaviour',
] as const;

const ajv = new Ajv2020({ allErrors: true, useDefaults: true, strict: false });
const validateMetadata = ajv.compile(schema);

function formatValidationErrors(errors: ErrorObject[] | null | undefined): string {
  return (errors ?? [])
    .map((error) => `${error.instancePath || '(front matter)'} ${error.message ?? 'is invalid'}`)
    .join('; ');
}

function relativePath(repositoryRoot: string, filePath: string): string {
  return relative(repositoryRoot, filePath).split(sep).join('/');
}

function isInsideRoot(root: string, candidate: string): boolean {
  const rootWithSeparator = root.endsWith(sep) ? root : `${root}${sep}`;
  return candidate === root || candidate.startsWith(rootWithSeparator);
}

function safeChildPath(root: string, child: string): string {
  const candidate = resolve(root, child);
  if (!isInsideRoot(root, candidate)) {
    throw new SpecificationError(`Specification path escapes permitted root: ${child}`);
  }
  return candidate;
}

export async function discoverMarkdownFiles(specsRoot: string): Promise<string[]> {
  const root = resolve(specsRoot);
  const files: string[] = [];

  async function visit(directory: string): Promise<void> {
    if (!isInsideRoot(root, directory)) {
      throw new SpecificationError(`Specification directory escapes permitted root: ${directory}`);
    }

    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((left, right) => left.name.localeCompare(right.name));
    for (const entry of entries) {
      if (entry.name.startsWith('.')) continue;
      const entryPath = safeChildPath(directory, entry.name);
      if (entry.isDirectory()) {
        await visit(entryPath);
      } else if (entry.isFile() && entry.name.toLowerCase().endsWith('.md')) {
        files.push(entryPath);
      }
    }
  }

  await visit(root);
  return files;
}

export async function parseSpecification(
  filePath: string,
  repositoryRoot: string,
): Promise<ParsedFile> {
  const raw = await readFile(filePath, 'utf8');
  const sourcePath = relativePath(repositoryRoot, filePath);
  let document: matter.GrayMatterFile<string>;
  try {
    document = matter(raw);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    throw new SpecificationError(`${sourcePath}: invalid front matter: ${reason}`);
  }

  if (!validateMetadata(document.data)) {
    throw new SpecificationError(
      `${sourcePath}: invalid front matter: ${formatValidationErrors(validateMetadata.errors)}`,
    );
  }

  const metadata = document.data as unknown as SpecificationMetadata;
  for (const field of arrayFields) {
    if (!Array.isArray(metadata[field])) {
      throw new SpecificationError(`${sourcePath}: ${field} must be an array`);
    }
  }
  if (metadata.entity_type === 'component' && typeof metadata.owner !== 'string') {
    throw new SpecificationError(`${sourcePath}: component owner must be a single string`);
  }
  if (metadata.workflow_order !== undefined && metadata.workflow_id === undefined) {
    throw new SpecificationError(`${sourcePath}: workflow_order requires workflow_id`);
  }

  return {
    metadata,
    sourcePath,
    body: document.content.trim(),
  };
}

function collectReferences(specification: ParsedFile): string[] {
  return [...specification.metadata.depends_on, ...specification.metadata.connects_to];
}

function addRelation(
  relationMap: Map<string, { source: string; target: string; relations: Set<EdgeRelation> }>,
  source: string,
  target: string,
  relation: EdgeRelation,
): void {
  const id = `${source}->${target}`;
  const edge = relationMap.get(id) ?? { source, target, relations: new Set<EdgeRelation>() };
  edge.relations.add(relation);
  relationMap.set(id, edge);
}

function validateReferences(specifications: ParsedFile[]): void {
  const knownIds = new Set(specifications.map(({ metadata }) => metadata.id));
  for (const specification of specifications) {
    for (const reference of collectReferences(specification)) {
      if (!knownIds.has(reference)) {
        throw new SpecificationError(
          `${specification.sourcePath}: unresolved relationship reference "${reference}"`,
        );
      }
    }
    const { workflow_id: workflowId } = specification.metadata;
    if (workflowId !== undefined && !knownIds.has(workflowId)) {
      throw new SpecificationError(
        `${specification.sourcePath}: unresolved workflow reference "${workflowId}"`,
      );
    }
  }

  const workflows = specifications.filter(({ metadata }) => metadata.entity_type === 'workflow-step');
  const workflowIds = new Set(workflows.map(({ metadata }) => metadata.id));
  const orders = new Map<string, Set<number>>();
  for (const specification of specifications) {
    const { workflow_id: workflowId, workflow_order: workflowOrder } = specification.metadata;
    if (workflowOrder === undefined || workflowId === undefined) continue;
    const workflowOrders = orders.get(workflowId) ?? new Set<number>();
    if (workflowOrders.has(workflowOrder)) {
      throw new SpecificationError(
        `${specification.sourcePath}: duplicate workflow_order ${workflowOrder} for ${workflowId}`,
      );
    }
    workflowOrders.add(workflowOrder);
    orders.set(workflowId, workflowOrders);
  }

  for (const workflow of workflows) {
    for (const pathId of workflow.metadata.depends_on) {
      const pathEntity = specifications.find(({ metadata }) => metadata.id === pathId);
      if (pathEntity?.metadata.workflow_id !== workflow.metadata.id) {
        throw new SpecificationError(
          `${workflow.sourcePath}: workflow path reference "${pathId}" has mismatched workflow_id`,
        );
      }
    }
  }

  for (const specification of specifications) {
    if (
      specification.metadata.workflow_id !== undefined &&
      !workflowIds.has(specification.metadata.workflow_id)
    ) {
      throw new SpecificationError(
        `${specification.sourcePath}: workflow_id "${specification.metadata.workflow_id}" is not a workflow specification`,
      );
    }
  }
}

function buildWorkflows(specifications: ParsedFile[]): WorkflowTrace[] {
  return specifications
    .filter(({ metadata }) => metadata.entity_type === 'workflow-step')
    .map(({ metadata, sourcePath }) => ({
      id: metadata.id,
      name: metadata.name,
      description: metadata.description,
      sourcePath,
      path: [...metadata.depends_on],
    }))
    .sort((left, right) => left.id.localeCompare(right.id));
}

export function buildMap(specifications: ParsedFile[], schemaId = schema.$id): GeneratedMap {
  const ids = new Set<string>();
  for (const specification of specifications) {
    if (ids.has(specification.metadata.id)) {
      throw new SpecificationError(
        `${specification.sourcePath}: duplicate entity ID "${specification.metadata.id}"`,
      );
    }
    ids.add(specification.metadata.id);
  }

  validateReferences(specifications);
  const relationMap = new Map<
    string,
    { source: string; target: string; relations: Set<EdgeRelation> }
  >();
  for (const specification of specifications) {
    for (const target of specification.metadata.depends_on) {
      addRelation(relationMap, specification.metadata.id, target, 'depends_on');
    }
    for (const target of specification.metadata.connects_to) {
      addRelation(relationMap, specification.metadata.id, target, 'connects_to');
    }
  }

  const workflows = buildWorkflows(specifications);
  for (const workflow of workflows) {
    for (let index = 1; index < workflow.path.length; index += 1) {
      addRelation(relationMap, workflow.path[index - 1], workflow.path[index], 'workflow');
    }
  }

  const edges = [...relationMap.values()]
    .map(({ source, target, relations }) => ({
      id: `${source}->${target}`,
      source,
      target,
      relations: [...relations].sort(),
    }))
    .sort((left, right) => left.id.localeCompare(right.id));
  const entities = specifications
    .map(({ metadata, sourcePath, body }) => ({ ...metadata, sourcePath, body }))
    .sort((left, right) => left.id.localeCompare(right.id));

  return {
    generatedHeader: GENERATED_HEADER,
    schemaId,
    entities,
    edges,
    workflows,
    validation: {
      entityCount: entities.length,
      edgeCount: edges.length,
      workflowCount: workflows.length,
    },
  };
}

function generatedSchemaValues(): string {
  const properties = schema.properties as Record<string, { enum?: string[] }>;
  const entries: [string, string[] | undefined][] = [
    ['ENTITY_TYPES', properties.entity_type.enum],
    ['PLANES', properties.plane.enum],
    ['SCOPES', properties.scope.enum],
    ['STATUSES', properties.status.enum],
    ['RISKS', properties.risk.enum],
    ['ACTOR_TYPES', properties.actor_type.enum],
  ];
  const body = entries
    .map(([name, values]) => {
      const serializedValues = JSON.stringify(values ?? []);
      return `export const ${name} = ${serializedValues} as const;`;
    })
    .join('\n\n');
  const types = [
    ['EntityType', 'ENTITY_TYPES'],
    ['Plane', 'PLANES'],
    ['Scope', 'SCOPES'],
    ['Status', 'STATUSES'],
    ['Risk', 'RISKS'],
    ['ActorType', 'ACTOR_TYPES'],
  ]
    .map(([name, values]) => `export type ${name} = (typeof ${values})[number];`)
    .join('\n');
  return `// GENERATED FILE — DO NOT EDIT MANUALLY. Regenerate with \`npm run generate\`.\n\n${body}\n\n${types}\n`;
}

export async function generateProjectMap(
  repositoryRoot: string,
  outputPath: string,
  schemaValuesPath: string,
): Promise<GeneratedMap> {
  const specsRoot = resolve(repositoryRoot, 'specs');
  const files = await discoverMarkdownFiles(specsRoot);
  const specifications: ParsedFile[] = [];
  for (const file of files) {
    specifications.push(await parseSpecification(file, repositoryRoot));
  }
  const map = buildMap(specifications);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(`${outputPath}`, `${JSON.stringify(map, null, 2)}\n`, 'utf8');
  await mkdir(dirname(schemaValuesPath), { recursive: true });
  await writeFile(schemaValuesPath, generatedSchemaValues(), 'utf8');
  return map;
}

export function assertSafeRepositoryPath(repositoryRoot: string, candidate: string): void {
  const root = resolve(repositoryRoot);
  const resolved = resolve(candidate);
  if (!isInsideRoot(root, resolved)) {
    throw new SpecificationError(`Specification path escapes permitted root: ${candidate}`);
  }
}
